const fs = require('fs');
const path = require('path');

const dict = {
  'Nermai பயிற்சி மையம்': 'Nermai Coaching Center',
  'தேர்வுக்கான விண்ணப்பங்கள் ஏற்கப்படுகின்றன. கடைசி தேதி: 30 செப்டம்பர் 2024.': 'Exam applications are accepted. Last date: 30 September 2024.',
  'UPSC Prelims 2025 new batch starts Oct 1. Seats limited.': 'New batch for UPSC Prelims 2025 starts Oct 1. Seats limited.',
  'தமிழ்Nாடு காவல்துறை': 'Tamil Nadu Police',
  'தேர்வுக்கான மாதிரி வினாக்கள் கிடைக்கும்.': 'Model questions available for the exam.',
  'Nermaiயின் வழிகாட்டுதலால் மட்டுமே இN்த வெற்றி சாத்தியமானது.': 'This success was possible only through Nermai\'s guidance.',
  'தினமும் 8 மணி Nேரம் படித்தேன். Nermai அகாடமி என் தன்னம்பிக்கையை வளர்த்தது.': 'I studied 8 hours a day. Nermai Academy boosted my confidence.',
  'Nermaiயில் படித்ததால்': 'By studying at Nermai',
  'தமிழ் வழியில் UPSC பயிற்சி கிடைப்பது மிகவும் அரிது. Nermai அதை சாத்தியமாக்கியது.': 'Getting UPSC coaching in Tamil is very rare. Nermai made it possible.',
  'Nermaiயில் பயிற்சி பெற்று வெற்றி பெற்றவர்களின் Nermaiயான கருத்துகள்.': 'Honest reviews from successful Nermai students.',
  'Nermai IAS Academy-ல் Testimonials from successful students.': 'Testimonials from successful students at Nermai IAS Academy.',
  'உங்கள் தயாரிப்பை மேம்படுத்த Nாங்கள் வழங்கும் இலவச வளங்கள்.': 'Free resources we provide to enhance your preparation.',
  'சமீபத்திய Announcements, கட்-ஆஃப் மார்க்குகள், மற்றும் முக்கிய தகவல்கள்.': 'Latest announcements, cut-off marks, and important info.',
  'Admin panel மூலம் Announcements சேர்க்கவும்': 'Add Announcements via Admin panel',
  'Nermaiயான கல்வி': 'Honest Education',
  'Sure Path to Success': 'Sure Path to Success',
  'Nermai அகாடமியின் Nேரடி வகுப்பறை மற்றும் Nிகழ்வுகளின் புகைப்படங்கள்.': 'Photos of Nermai Academy classes and events.',
  'Nermai எN்த தேர்வுகளுக்கான பயிற்சி வழங்குகிறது?': 'What exams does Nermai coach for?',
  'மற்றும் SSC போன்ற போட்டித் தேர்வுகளுக்கான விரிவான பயிற்சி வழங்கப்படுகிறது.': 'and SSC competitive exams comprehensive coaching provided.',
  'வகுப்புகள் ஆன்லைனிலா, offline-லா?': 'Are classes online or offline?',
  'Nermai Class Platform மூலம் சிறN்த ஆன்லைன் learning experience வழங்கப்படுகிறது. Nீங்கள் எங்கிருN்தும், எN்த Nேரமும் வகுப்புகளில் கலN்து கொள்ளலாம்.': 'Nermai Class Platform provides the best online learning experience. You can attend classes from anywhere, anytime.',
  'எப்படி சேருவது?': 'How to join?',
  'தலைப்பில் உள்ள "Enroll / Login" button மூலம் Class Platform-க்கு சென்று பதிவு செய்து கொள்ளலாம். எN்த ஒரு கேள்வியும் இருN்தால் WhatsApp அல்லது Contact Us பக்கம் மூலம் தொடர்பு கொள்ளவும்.': 'Click Enroll / Login in the header to register. Contact via WhatsApp or Contact Us page for any queries.',
  'Study materials கிடைக்குமா?': 'Will I get study materials?',
  'ஆம். உங்கள் தேர்வுக்கேற்ப பிரத்யேகமான study materials, handouts, previous year papers மற்றும் revision notes வழங்கப்படும்.': 'Yes. Exclusive study materials, handouts, previous year papers and revision notes will be provided.',
  'கட்டணம் எவ்வளவு?': 'What is the fee?',
  'கட்டணம் course மற்றும் batch-ஐ பொறுத்து மாறுபடும். விரிவான கட்டண விவரங்களுக்கு எங்கள் Class Platform-ஐ பார்வையிடவும் அல்லது Nேரடியாக தொடர்பு கொள்ளவும்.': 'Fee varies by course and batch. Visit our Class Platform or contact directly for details.',
  'IAS/IPS-Nிலையிலான தமிழ்Nாடு அரசு பதவிகளுக்கான முதல்Nிலை தேர்வு.': 'Preliminary exam for IAS/IPS level TN govt posts.',
  'போன்ற பதவிகள்.': 'and similar posts.',
  'வாலியாஸ், Typist, Steno-Typist, Junior Assistant பதவிகள். அதிக வேலைவாய்ப்பு.': 'Typist, Steno-Typist, Junior Assistant posts. High job opportunities.',
  'அனைத்தையும் உள்ளடக்கிய கூட்டு தேர்வு.': 'Combined exam including all.',
  'மற்றும் மத்திய அரசு சேவைகளுக்கான ஆரம்ப தேர்வு.': 'and initial exam for central govt services.',
  'தமிழ் மொழி வழியில்': 'In Tamil medium',
  'உடல் தகுதி +': 'Physical Fitness +',
  'தேர்வுக்கான': 'exam',
  'தேர்வு வகைகள்': 'Exam Categories',
  'எN்த தேர்வுக்கு': 'Which exam',
  'தயாராகிறீர்கள்?': 'are you preparing for?',
  'TNPSC முதல் UPSC வரை — அனைத்து அரசு வேலை தேர்வுகளுக்கும்': 'From TNPSC to UPSC — for all govt job exams',
  'தமிழ் வழியில் தரமான பயிற்சி.': 'Quality coaching in Tamil medium.',
  'பதிவு செய்': 'Register',
  'மாணவர் Name *': 'Student Name *',
  'பதவி / தேர்வு': 'Role / Exam',
  'கருத்து *': 'Quote *',
  'கருத்து சேர்': 'Add Quote',
  'கருத்துகள் (': 'Quotes (',
  'கருத்துகள் இல்லை': 'No Quotes',
  'படம் தேவை (URL missing)': 'Image required (URL missing)',
  'படம் சேர்க்கப்பட்டது!': 'Image added!',
  'இN்த படத்தை Delete?': 'Delete this image?',
  'கேலரி (Gallery)': 'Gallery',
  'தலைப்பு / விவரம் (Caption - Optional)': 'Caption (Optional)',
  'மாணவர் பாராட்டு விழா 2024': 'Student Felicitation 2024',
  'கேலரியில் சேர்': 'Add to Gallery',
  'புகைப்படங்கள் (': 'Photos (',
  'படங்கள் இல்லை': 'No images',
  'குறைN்தது 4 characters தேவை': 'Minimum 4 characters required',
  'Nீக்கு': 'Delete',
  'குறைN்தது': 'At least',
  'இN்த': 'This',
  'Nீக்கவா': 'Delete',
  'Nீக்கப்பட்டது': 'Deleted',
  'அறிவிப்பு': 'Announcement',
  'விவரம்': 'Details',
  'முழு': 'Full',
  'முன்னுரிமை': 'Priority',
  'தேதி': 'Date',
  'சேர்': 'Add',
  'தற்போதைய': 'Current',
  'இல்லை': 'None',
  'ஆனது': 'done',
  'பெயர்': 'Name',
  'மற்றும்': 'and',
  'தேவை': 'required',
  'வெற்றியாளர்கள்': 'Winners',
  'தேர்வு': 'Exam',
  'ஆண்டு': 'Year',
  'கருத்து': 'Quote',
  'மாணவர்': 'Student',
  'பதவி': 'Post',
  'படம்': 'Image',
  'கேலரி': 'Gallery',
  'தலைப்பு': 'Title',
  'புகைப்படங்கள்': 'Photos',
  'படங்கள்': 'Images',
  'வழிகாட்டுதலால்': 'Guidance',
  'மட்டுமே': 'only',
  'வெற்றி': 'Success',
  'சாத்தியமானது': 'Possible',
  'தினமும்': 'Daily',
  'மணி': 'Hour',
  'Nேரம்': 'Time',
  'படித்தேன்': 'Studied',
  'அகாடமி': 'Academy',
  'என்': 'My',
  'தன்னம்பிக்கையை': 'Confidence',
  'வளர்த்தது': 'developed',
  'படித்ததால்': 'Studied',
  'தமிழ்': 'Tamil',
  'வழியில்': 'Way',
  'பயிற்சி': 'Training',
  'கிடைப்பது': 'getting',
  'மிகவும்': 'very',
  'அரிது': 'rare',
  'அதை': 'it',
  'சாத்தியமாக்கியது': 'made possible',
  'பயிற்சி பெற்று': 'trained',
  'பெற்றவர்களின்': 'received',
  'யான': '',
  'வழங்கும்': 'providing',
  'இலவச': 'Free',
  'வளங்கள்': 'Resources',
  'உங்கள்': 'Your',
  'தயாரிப்பை': 'preparation',
  'மேம்படுத்த': 'improve',
  'Nாங்கள்': 'We',
  'சமீபத்திய': 'Latest',
  'கட்-ஆஃப்': 'Cut-off',
  'மார்க்குகள்': 'Marks',
  'முக்கிய': 'Important',
  'தகவல்கள்': 'Information',
  'மூலம்': 'via',
  'சேர்க்கவும்': 'add',
  'கல்வி': 'Education',
  'வகுப்பறை': 'Classroom',
  'Nிகழ்வுகளின்': 'Events',
  'எN்த': 'Which',
  'வழங்குகிறது': 'provides',
  'விரிவான': 'comprehensive',
  'ஆன்லைனிலா': 'Online',
  'சிறN்த': 'Best',
  'ஆன்லைன்': 'Online',
  'எங்கிருN்தும்': 'Anywhere',
  'கலN்து': 'Attend',
  'கொள்ளலாம்': 'Can',
  'எப்படி': 'How',
  'சேருவது': 'to join',
  'உள்ள': 'in',
  'சென்று': 'go',
  'பதிவு': 'Register',
  'செய்து': 'do',
  'ஒரு': 'One',
  'கேள்வியும்': 'Question',
  'இருN்தால்': 'If',
  'அல்லது': 'or',
  'பக்கம்': 'Page',
  'தொடர்பு': 'Contact',
  'கொள்ளவும்': 'please',
  'கிடைக்குமா': 'Available',
  'ஆம்': 'Yes',
  'தேர்வுக்கேற்ப': 'Exam oriented',
  'பிரத்யேகமான': 'Exclusive',
  'வழங்கப்படும்': 'will be provided',
  'கட்டணம்': 'Fee',
  'எவ்வளவு': 'How much',
  'பொறுத்து': 'depends',
  'மாறுபடும்': 'varies',
  'விவரங்களுக்கு': 'for details',
  'எங்கள்': 'Our',
  'பார்வையிடவும்': 'visit',
  'Nேரடியாக': 'Directly',
  'Nிலையிலான': 'level',
  'அரசு': 'Govt',
  'பதவிகளுக்கான': 'posts',
  'முதல்Nிலை': 'Prelims',
  'அதிக': 'High',
  'வேலைவாய்ப்பு': 'Job opportunity',
  'அனைத்தையும்': 'All',
  'உள்ளடக்கிய': 'included',
  'கூட்டு': 'Combined',
  'மத்திய': 'Central',
  'சேவைகளுக்கான': 'Services',
  'ஆரம்ப': 'Initial',
  'மொழி': 'Language',
  'உடல்': 'Physical',
  'தகுதி': 'Fitness',
  'வகைகள்': 'Types',
  'தயாராகிறீர்கள்': 'Preparing',
  'முதல்': 'to',
  'வரை': 'till',
  'வேலை': 'Job',
  'தேர்வுகளுக்கும்': 'Exams',
  'தரமான': 'Quality',
  'செய்': 'Do',
  'விவரம்': 'Details'
};

function processDir(dir) {
  const files = fs.readdirSync(dir);
  for (const file of files) {
    const fullPath = path.join(dir, file);
    if (fs.statSync(fullPath).isDirectory()) {
      processDir(fullPath);
    } else if (fullPath.endsWith('.jsx') || fullPath.endsWith('.js')) {
      let content = fs.readFileSync(fullPath, 'utf8');
      let changed = false;
      for (const [ta, en] of Object.entries(dict)) {
        if (content.includes(ta)) {
          content = content.split(ta).join(en);
          changed = true;
        }
      }
      
      // Finally wipe out any remaining Tamil characters safely
      if (/[\\u0B80-\\u0BFF]/.test(content)) {
        content = content.replace(/[\\u0B80-\\u0BFF]/g, '');
        changed = true;
      }
      
      if (changed) {
        fs.writeFileSync(fullPath, content);
        console.log('Updated ' + fullPath);
      }
    }
  }
}

processDir('C:/Users/ASUS/Videos/start_up/NERMAI_STATIC/src');
